# Generated by Django 2.1 on 2018-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=25)),
                ('Student_Id', models.CharField(max_length=25, unique=True)),
                ('Password', models.CharField(max_length=25)),
                ('Confirm_PassWord', models.CharField(max_length=25)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Contact_No', models.IntegerField(unique=True)),
                ('Password_Key', models.CharField(max_length=25)),
            ],
        ),
    ]
