# Generated by Django 2.1.2 on 2018-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_auto_20181026_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
                ('questio_name', models.CharField(max_length=25)),
                ('option_1', models.CharField(max_length=25)),
                ('option_2', models.CharField(max_length=25)),
                ('option_3', models.CharField(max_length=25)),
                ('option_4', models.CharField(max_length=25)),
                ('currect_answer', models.CharField(max_length=25)),
            ],
        ),
    ]
